const date = new Date();

export const houseFormData = [
   {
      id: "1_0",
      title: "Contact information",
      component: "Contact",
   },
   {
      id: "2_0",
      title: "Additional",
      parentObjectName: "houseDetails",
      inputs: [
         {
            id: "2_1",
            placeholder: "Rooms",
            type: "number",
            name: "houseDetails.room",
         },
         {
            id: "2_2",
            placeholder: "Beds",
            type: "number",
            name: "houseDetails.beds",
         },
         {
            id: "2_3",
            placeholder: "Baths",
            type: "number",
            name: "houseDetails.bath",
         },
         {
            id: "2_4",
            placeholder: "Garages",
            type: "number",
            name: "houseDetails.garage",
         },
         {
            id: "2_5",
            placeholder: "Year bulid",
            type: "number",
            name: "houseDetails.yearBuilt",
            min: 1700,
            max: date.getFullYear(),
         },
         {
            id: "2_6",
            placeholder: "Home area (sqft)",
            type: "number",
            name: "houseDetails.area",
            min: "20",
         },
      ],
   },
   {
      id: "3_0",
      title: "Price",
      inputs: [
         { id: "3_1", placeholder: "Price ($)", type: "number", name: "price" },
         {
            id: "3_2",
            placeholder: "Sale Price ($)",
            type: "number",
            name: "salePrice",
         },
      ],
   },
   {
      id: "4_0",
      title: "Location",
      inputs: [
         { id: "4_1", placeholder: "Address", type: "text", name: "address" },
         { id: "4_2", placeholder: "Country", type: "text", name: "country" },
         { id: "4_3", placeholder: "Region", type: "text", name: "region" },
         { id: "4_4", placeholder: "City", type: "text", name: "city" },
         { id: "4_5", placeholder: "Zip Code", type: "text", name: "zipCode" },
      ],
   },
   {
      id: "5_0",
      title: "Media",
      component: "Media",
   },
   // {
   //    id: 6,
   //    title: "Amenities",
   //    parentObjectName: "componentsDto",
   //    inputs: [
   //       {
   //          id: 1,
   //          placeholder: "Air conditioning",
   //          type: "checkbox",
   //          name: "componentsDto.airCondition",
   //       },
   //       {
   //          id: 2,
   //          placeholder: "Courtyard",
   //          type: "checkbox",
   //          name: "componentsDto.courtyard",
   //       },
   //       {
   //          id: 3,
   //          placeholder: "Furniture",
   //          type: "checkbox",
   //          name: "componentsDto.furniture",
   //       },
   //       {
   //          id: 4,
   //          placeholder: "Gas Stove",
   //          type: "checkbox",
   //          name: "componentsDto.gasStove",
   //       },
   //       {
   //          id: 5,
   //          placeholder: "Internet",
   //          type: "checkbox",
   //          name: "componentsDto.internet",
   //       },
   //       {
   //          id: 6,
   //          placeholder: "Tv",
   //          type: "checkbox",
   //          name: "componentsDto.tv",
   //       },
   //       // { id: 1, placeholder: "Air conditioning", type: "checkbox", name: "airCondition" },
   //       // { id: 2, placeholder: "Lawn", type: "checkbox", name: "" },
   //       // { id: 3, placeholder: "Dining Room", type: "checkbox", name: "" },
   //       // { id: 4, placeholder: "Waterfront", type: "checkbox", name: "" },
   //       // { id: 5, placeholder: "Barbecue", type: "checkbox", name: "" },
   //       // { id: 6, placeholder: "Microwave", type: "checkbox", name: "" },
   //       // { id: 7, placeholder: "Fireplace", type: "checkbox", name: "" },
   //       // { id: 8, placeholder: "Parking", type: "checkbox", name: "parking" },
   //       // { id: 9, placeholder: "Dryer", type: "checkbox", name: "" },
   //       // { id: 10, placeholder: "Outdoor Shower", type: "checkbox", name: "" },
   //       // { id: 11, placeholder: "Pets Allowed", type: "checkbox", name: "" },
   //       // { id: 12, placeholder: "Doorman", type: "checkbox", name: "" },
   //       // { id: 13, placeholder: "Gym", type: "checkbox", name: "" },
   //       // { id: 14, placeholder: "Refrigerator", type: "checkbox", name: "" },
   //       // {
   //       //    id: 15,
   //       //    placeholder: "Unit Washer/Dryer",
   //       //    type: "checkbox",
   //       //    name: "",
   //       // },
   //       // { id: 16, placeholder: "Central Heating", type: "checkbox", name: "" },
   //       // { id: 17, placeholder: "Laundry", type: "checkbox", name: "" },
   //       // { id: 18, placeholder: "Stunning views", type: "checkbox", name: "" },
   //       // { id: 19, placeholder: "Onsite Parking", type: "checkbox", name: "" },
   //       // { id: 20, placeholder: "Cleaning Service", type: "checkbox", name: "" },
   //    ],
   // },
   // {
   //    id: 7,
   //    title: "Nearby",
   //    parentObjectName: "homeAmenitiesDto",
   //    inputs: [
   //       {
   //          id: 2,
   //          placeholder: "Bus Stop",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.busStop",
   //       },
   //       {
   //          id: 3,
   //          placeholder: "Garden",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.garden",
   //       },
   //       {
   //          id: 4,
   //          placeholder: "Market",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.market",
   //       },
   //       {
   //          id: 5,
   //          placeholder: "Park",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.park",
   //       },
   //       {
   //          id: 6,
   //          placeholder: "Parking",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.parking",
   //       },
   //       {
   //          id: 7,
   //          placeholder: "School",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.school",
   //       },
   //       {
   //          id: 8,
   //          placeholder: "Stadium",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.stadium",
   //       },
   //       {
   //          id: 9,
   //          placeholder: "Subway",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.subway",
   //       },
   //       {
   //          id: 10,
   //          placeholder: "Super Market",
   //          type: "checkbox",
   //          name: "homeAmenitiesDto.superMarket",
   //       },
   //    ],
   // },
];
